INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 5, '에너지 가격 상승', 0, SYSTIMESTAMP - INTERVAL '4' DAY);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 6, '통신 서비스 개선', 1, SYSTIMESTAMP - INTERVAL '5' DAY);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 7, '부동산 시장 활발', 1, SYSTIMESTAMP - INTERVAL '2' DAY);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 8, '제조업 성장', 1, SYSTIMESTAMP - INTERVAL '1' DAY);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 9, '자동차 판매 증가', 1, SYSTIMESTAMP - INTERVAL '3' DAY);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 7, '부동산 시장 활발', 1, SYSTIMESTAMP - INTERVAL '2' DAY);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 8, '제조업 성장', 1, SYSTIMESTAMP - INTERVAL '1' DAY);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 9, '자동차 판매 증가', 1, SYSTIMESTAMP - INTERVAL '3' DAY);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 7, '부동산 시장 활발', 1, SYSTIMESTAMP - INTERVAL '2' DAY);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 8, '제조업 성장', 1, SYSTIMESTAMP - INTERVAL '1' DAY);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 9, '자동차 판매 증가', 1, SYSTIMESTAMP - INTERVAL '3' DAY);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 7, '부동산 시장 활발', 1, SYSTIMESTAMP - INTERVAL '2' DAY);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 8, '제조업 성장', 1, SYSTIMESTAMP - INTERVAL '1' DAY);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 9, '자동차 판매 증가', 1, SYSTIMESTAMP - INTERVAL '1' DAY);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 7, '부동산 시장 활발', 1, SYSTIMESTAMP - INTERVAL '2' DAY);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 8, '제조업 성장', 1, SYSTIMESTAMP - INTERVAL '1' DAY);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 9, '자동차 판매 증가', 1, SYSTIMESTAMP - INTERVAL '3' DAY);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 8, '제조업 성장', 1, SYSTIMESTAMP - INTERVAL '1' DAY);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 9, '자동차 판매 증가', 1, SYSTIMESTAMP - INTERVAL '3' DAY);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 8, '제조업 성장', 1, SYSTIMESTAMP - INTERVAL '1' DAY);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 9, '자동차 판매 증가', 1, SYSTIMESTAMP - INTERVAL '4' DAY);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 9, '자동차 판매 증가', 1, SYSTIMESTAMP - INTERVAL '1' DAY);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 9, '자동차 판매 증가', 1, SYSTIMESTAMP - INTERVAL '1' DAY);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 9, '자동차 판매 증가', 1, SYSTIMESTAMP - INTERVAL '2' DAY);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 9, '자동차 판매 증가', 1, SYSTIMESTAMP - INTERVAL '3' DAY);




INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE) VALUES (NEWS_SEQ.NEXTVAL, '헬스케어 혁신', 3, 1, '헬스뉴스', 'http://healthnews.com/3', SYSTIMESTAMP - INTERVAL '3' DAY);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE) VALUES (NEWS_SEQ.NEXTVAL, '소비자 신뢰 증가', 4, 1, '소비자리포트', 'http://consumerreport.com/4', SYSTIMESTAMP - INTERVAL '1' HOUR);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE) VALUES (NEWS_SEQ.NEXTVAL, '에너지 시장의 변화', 5, 0, '에너지뉴스', 'http://energynews.com/5', SYSTIMESTAMP - INTERVAL '1' DAY);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE) VALUES (NEWS_SEQ.NEXTVAL, '통신 기술 발전', 6, 1, '통신리포트', 'http://communicationreport.com/6', SYSTIMESTAMP - INTERVAL '2' DAY);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE) VALUES (NEWS_SEQ.NEXTVAL, '부동산 투자 증가', 7, 1, '부동산신문', 'http://realestatenews.com/7', SYSTIMESTAMP - INTERVAL '1' DAY);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE) VALUES (NEWS_SEQ.NEXTVAL, '헬스케어 혁신', 3, 1, '헬스뉴스', 'http://healthnews.com/3', SYSTIMESTAMP - INTERVAL '4' DAY);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE) VALUES (NEWS_SEQ.NEXTVAL, '소비자 신뢰 증가', 4, 1, '소비자리포트', 'http://consumerreport.com/4', SYSTIMESTAMP - INTERVAL '5' HOUR);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE) VALUES (NEWS_SEQ.NEXTVAL, '에너지 시장의 변화', 5, 0, '에너지뉴스', 'http://energynews.com/5', SYSTIMESTAMP - INTERVAL '3' DAY);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE) VALUES (NEWS_SEQ.NEXTVAL, '통신 기술 발전', 6, 1, '통신리포트', 'http://communicationreport.com/6', SYSTIMESTAMP - INTERVAL '1' DAY);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE) VALUES (NEWS_SEQ.NEXTVAL, '부동산 투자 증가', 7, 1, '부동산신문', 'http://realestatenews.com/7', SYSTIMESTAMP - INTERVAL '2' DAY);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE) VALUES (NEWS_SEQ.NEXTVAL, '헬스케어 혁신', 3, 1, '헬스뉴스', 'http://healthnews.com/3', SYSTIMESTAMP - INTERVAL '2' DAY);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE) VALUES (NEWS_SEQ.NEXTVAL, '소비자 신뢰 증가', 4, 1, '소비자리포트', 'http://consumerreport.com/4', SYSTIMESTAMP - INTERVAL '1' HOUR);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE) VALUES (NEWS_SEQ.NEXTVAL, '에너지 시장의 변화', 5, 0, '에너지뉴스', 'http://energynews.com/5', SYSTIMESTAMP - INTERVAL '4' DAY);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE) VALUES (NEWS_SEQ.NEXTVAL, '통신 기술 발전', 6, 1, '통신리포트', 'http://communicationreport.com/6', SYSTIMESTAMP - INTERVAL '5' DAY);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE) VALUES (NEWS_SEQ.NEXTVAL, '부동산 투자 증가', 7, 1, '부동산신문', 'http://realestatenews.com/7', SYSTIMESTAMP - INTERVAL '2' DAY);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE) VALUES (NEWS_SEQ.NEXTVAL, '에너지 시장의 변화', 5, 0, '에너지뉴스', 'http://energynews.com/5', SYSTIMESTAMP - INTERVAL '4' DAY);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE) VALUES (NEWS_SEQ.NEXTVAL, '통신 기술 발전', 6, 1, '통신리포트', 'http://communicationreport.com/6', SYSTIMESTAMP - INTERVAL '5' DAY);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE) VALUES (NEWS_SEQ.NEXTVAL, '부동산 투자 증가', 7, 1, '부동산신문', 'http://realestatenews.com/7', SYSTIMESTAMP - INTERVAL '2' DAY);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE) VALUES (NEWS_SEQ.NEXTVAL, '에너지 시장의 변화', 5, 0, '에너지뉴스', 'http://energynews.com/5', SYSTIMESTAMP - INTERVAL '1' DAY);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE) VALUES (NEWS_SEQ.NEXTVAL, '통신 기술 발전', 6, 1, '통신리포트', 'http://communicationreport.com/6', SYSTIMESTAMP - INTERVAL '3' DAY);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE) VALUES (NEWS_SEQ.NEXTVAL, '부동산 투자 증가', 7, 1, '부동산신문', 'http://realestatenews.com/7', SYSTIMESTAMP - INTERVAL '3' DAY);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE) VALUES (NEWS_SEQ.NEXTVAL, '에너지 시장의 변화', 5, 0, '에너지뉴스', 'http://energynews.com/5', SYSTIMESTAMP - INTERVAL '2' DAY);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE) VALUES (NEWS_SEQ.NEXTVAL, '통신 기술 발전', 6, 1, '통신리포트', 'http://communicationreport.com/6', SYSTIMESTAMP - INTERVAL '3' DAY);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE) VALUES (NEWS_SEQ.NEXTVAL, '부동산 투자 증가', 7, 1, '부동산신문', 'http://realestatenews.com/7', SYSTIMESTAMP - INTERVAL '1' DAY);

COMMIT;
