-- 하루 전 날짜의 뉴스 기사와 커뮤니티 글 샘플
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE, CDATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 1, '어제 커뮤니티 글 내용', 1, SYSDATE - 1, SYSDATE);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE, CDATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 1, '어제 커뮤니티 글 내용', 1, SYSDATE - 1, SYSDATE);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE, CDATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 1, '어제 커뮤니티 글 내용', 1, SYSDATE - 1, SYSDATE);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE, CDATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 1, '어제 커뮤니티 글 내용', 1, SYSDATE - 1, SYSDATE);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE, CDATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 2, '어제 커뮤니티 글 내용', 1, SYSDATE - 1, SYSDATE);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE, CDATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 2, '어제 커뮤니티 글 내용', 1, SYSDATE - 1, SYSDATE);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE, CDATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 2, '어제 커뮤니티 글 내용', 1, SYSDATE - 1, SYSDATE);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE, CDATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 3, '어제 커뮤니티 글 내용', 1, SYSDATE - 1, SYSDATE);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE, CDATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 4, '어제 커뮤니티 글 내용', 1, SYSDATE - 1, SYSDATE);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE, CDATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 4, '어제 커뮤니티 글 내용', 1, SYSDATE - 1, SYSDATE);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE, CDATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 5, '어제 커뮤니티 글 내용', 1, SYSDATE - 1, SYSDATE);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE, CDATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 6, '어제 커뮤니티 글 내용', 1, SYSDATE - 1, SYSDATE);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE, CDATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 6, '어제 커뮤니티 글 내용', 1, SYSDATE - 1, SYSDATE);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE, CDATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 6, '어제 커뮤니티 글 내용', 1, SYSDATE - 1, SYSDATE);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE, CDATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 6, '어제 커뮤니티 글 내용', 1, SYSDATE - 1, SYSDATE);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE, CDATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 6, '어제 커뮤니티 글 내용', 1, SYSDATE - 1, SYSDATE);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE, CDATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 6, '어제 커뮤니티 글 내용', 1, SYSDATE - 1, SYSDATE);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE, CDATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 7, '어제 커뮤니티 글 내용', 1, SYSDATE - 1, SYSDATE);




INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '어제의 뉴스 제목', 1, 1, '언론사 이름', 'http://news.example.com', SYSDATE - 1, SYSDATE);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '어제의 뉴스 제목', 2, 1, '언론사 이름', 'http://news.example.com', SYSDATE - 1, SYSDATE);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '어제의 뉴스 제목', 2, 1, '언론사 이름', 'http://news.example.com', SYSDATE - 1, SYSDATE);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '어제의 뉴스 제목', 3, 1, '언론사 이름', 'http://news.example.com', SYSDATE - 1, SYSDATE);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '어제의 뉴스 제목', 3, 1, '언론사 이름', 'http://news.example.com', SYSDATE - 1, SYSDATE);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '어제의 뉴스 제목', 3, 1, '언론사 이름', 'http://news.example.com', SYSDATE - 1, SYSDATE);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '어제의 뉴스 제목', 3, 1, '언론사 이름', 'http://news.example.com', SYSDATE - 1, SYSDATE);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '어제의 뉴스 제목', 4, 1, '언론사 이름', 'http://news.example.com', SYSDATE - 1, SYSDATE);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '어제의 뉴스 제목', 4, 1, '언론사 이름', 'http://news.example.com', SYSDATE - 1, SYSDATE);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '어제의 뉴스 제목', 5, 1, '언론사 이름', 'http://news.example.com', SYSDATE - 1, SYSDATE);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '어제의 뉴스 제목', 5, 1, '언론사 이름', 'http://news.example.com', SYSDATE - 1, SYSDATE);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '어제의 뉴스 제목', 5, 1, '언론사 이름', 'http://news.example.com', SYSDATE - 1, SYSDATE);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '어제의 뉴스 제목', 5, 1, '언론사 이름', 'http://news.example.com', SYSDATE - 1, SYSDATE);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '어제의 뉴스 제목', 5, 1, '언론사 이름', 'http://news.example.com', SYSDATE - 1, SYSDATE);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '어제의 뉴스 제목', 5, 1, '언론사 이름', 'http://news.example.com', SYSDATE - 1, SYSDATE);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '어제의 뉴스 제목', 6, 1, '언론사 이름', 'http://news.example.com', SYSDATE - 1, SYSDATE);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '어제의 뉴스 제목', 7, 1, '언론사 이름', 'http://news.example.com', SYSDATE - 1, SYSDATE);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '어제의 뉴스 제목', 7, 1, '언론사 이름', 'http://news.example.com', SYSDATE - 1, SYSDATE);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '어제의 뉴스 제목', 7, 1, '언론사 이름', 'http://news.example.com', SYSDATE - 1, SYSDATE);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '어제의 뉴스 제목', 7, 1, '언론사 이름', 'http://news.example.com', SYSDATE - 1, SYSDATE);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '어제의 뉴스 제목', 7, 1, '언론사 이름', 'http://news.example.com', SYSDATE - 1, SYSDATE);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '어제의 뉴스 제목', 7, 1, '언론사 이름', 'http://news.example.com', SYSDATE - 1, SYSDATE);




-- 오늘 날짜의 뉴스 기사와 커뮤니티 글 샘플
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE, CDATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 1, '오늘 커뮤니티 글 내용', 1, SYSDATE, SYSDATE);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE, CDATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 1, '오늘 커뮤니티 글 내용', 1, SYSDATE, SYSDATE);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE, CDATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 1, '오늘 커뮤니티 글 내용', 1, SYSDATE, SYSDATE);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE, CDATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 1, '오늘 커뮤니티 글 내용', 1, SYSDATE, SYSDATE);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE, CDATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 2, '오늘 커뮤니티 글 내용', 1, SYSDATE, SYSDATE);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE, CDATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 3, '오늘 커뮤니티 글 내용', 1, SYSDATE, SYSDATE);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE, CDATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 3, '오늘 커뮤니티 글 내용', 1, SYSDATE, SYSDATE);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE, CDATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 4, '오늘 커뮤니티 글 내용', 1, SYSDATE, SYSDATE);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE, CDATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 4, '오늘 커뮤니티 글 내용', 1, SYSDATE, SYSDATE);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE, CDATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 4, '오늘 커뮤니티 글 내용', 1, SYSDATE, SYSDATE);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE, CDATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 4, '오늘 커뮤니티 글 내용', 1, SYSDATE, SYSDATE);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE, CDATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 4, '오늘 커뮤니티 글 내용', 1, SYSDATE, SYSDATE);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE, CDATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 4, '오늘 커뮤니티 글 내용', 1, SYSDATE, SYSDATE);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE, CDATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 5, '오늘 커뮤니티 글 내용', 1, SYSDATE, SYSDATE);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE, CDATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 5, '오늘 커뮤니티 글 내용', 1, SYSDATE, SYSDATE);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE, CDATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 6, '오늘 커뮤니티 글 내용', 1, SYSDATE, SYSDATE);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE, CDATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 6, '오늘 커뮤니티 글 내용', 1, SYSDATE, SYSDATE);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE, CDATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 7, '오늘 커뮤니티 글 내용', 1, SYSDATE, SYSDATE);
INSERT INTO COMMUNITY (COM_ID, STK_ID, CONTENT_TOKEN, COM_POS_LABEL, POST_DATE, CDATE) VALUES (COMMUNITY_SEQ.NEXTVAL, 7, '오늘 커뮤니티 글 내용', 1, SYSDATE, SYSDATE);


INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '오늘의 뉴스 제목', 1, 1, '언론사 이름', 'http://news.example.com', SYSDATE, SYSDATE);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '오늘의 뉴스 제목', 1, 1, '언론사 이름', 'http://news.example.com', SYSDATE, SYSDATE);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '오늘의 뉴스 제목', 1, 1, '언론사 이름', 'http://news.example.com', SYSDATE, SYSDATE);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '오늘의 뉴스 제목', 1, 1, '언론사 이름', 'http://news.example.com', SYSDATE, SYSDATE);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '오늘의 뉴스 제목', 1, 1, '언론사 이름', 'http://news.example.com', SYSDATE, SYSDATE);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '오늘의 뉴스 제목', 1, 1, '언론사 이름', 'http://news.example.com', SYSDATE, SYSDATE);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '오늘의 뉴스 제목', 2, 1, '언론사 이름', 'http://news.example.com', SYSDATE, SYSDATE);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '오늘의 뉴스 제목', 2, 1, '언론사 이름', 'http://news.example.com', SYSDATE, SYSDATE);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '오늘의 뉴스 제목', 2, 1, '언론사 이름', 'http://news.example.com', SYSDATE, SYSDATE);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '오늘의 뉴스 제목', 2, 1, '언론사 이름', 'http://news.example.com', SYSDATE, SYSDATE);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '오늘의 뉴스 제목', 3, 1, '언론사 이름', 'http://news.example.com', SYSDATE, SYSDATE);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '오늘의 뉴스 제목', 3, 1, '언론사 이름', 'http://news.example.com', SYSDATE, SYSDATE);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '오늘의 뉴스 제목', 4, 1, '언론사 이름', 'http://news.example.com', SYSDATE, SYSDATE);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '오늘의 뉴스 제목', 4, 1, '언론사 이름', 'http://news.example.com', SYSDATE, SYSDATE);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '오늘의 뉴스 제목', 4, 1, '언론사 이름', 'http://news.example.com', SYSDATE, SYSDATE);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '오늘의 뉴스 제목', 5, 1, '언론사 이름', 'http://news.example.com', SYSDATE, SYSDATE);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '오늘의 뉴스 제목', 5, 1, '언론사 이름', 'http://news.example.com', SYSDATE, SYSDATE);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '오늘의 뉴스 제목', 5, 1, '언론사 이름', 'http://news.example.com', SYSDATE, SYSDATE);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '오늘의 뉴스 제목', 5, 1, '언론사 이름', 'http://news.example.com', SYSDATE, SYSDATE);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '오늘의 뉴스 제목', 6, 1, '언론사 이름', 'http://news.example.com', SYSDATE, SYSDATE);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '오늘의 뉴스 제목', 7, 1, '언론사 이름', 'http://news.example.com', SYSDATE, SYSDATE);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '오늘의 뉴스 제목', 7, 1, '언론사 이름', 'http://news.example.com', SYSDATE, SYSDATE);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '오늘의 뉴스 제목', 7, 1, '언론사 이름', 'http://news.example.com', SYSDATE, SYSDATE);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '오늘의 뉴스 제목', 7, 1, '언론사 이름', 'http://news.example.com', SYSDATE, SYSDATE);
INSERT INTO NEWS (NEWS_ID, TITLE, STK_ID, NEWS_POS_LABEL, MEDIA_NAME, NEWS_URL, PUBLISHED_DATE, CDATE) VALUES (NEWS_SEQ.NEXTVAL, '오늘의 뉴스 제목', 7, 1, '언론사 이름', 'http://news.example.com', SYSDATE, SYSDATE);

COMMIT;