INSERT INTO TRAIT_STK (TRAIT_STK_ID,STK_ID,TRAIT_STK_RTN,TRAIT_STK_VOL,TRAIT_STK_RISK)
    VALUES (trait_stk_seq.nextval,1,10.78,7.1,2);
INSERT INTO TRAIT_STK (TRAIT_STK_ID,STK_ID,TRAIT_STK_RTN,TRAIT_STK_VOL,TRAIT_STK_RISK)
    VALUES (trait_stk_seq.nextval,2,9.78,6.1,2);
INSERT INTO TRAIT_STK (TRAIT_STK_ID,STK_ID,TRAIT_STK_RTN,TRAIT_STK_VOL,TRAIT_STK_RISK)
    VALUES (trait_stk_seq.nextval,3,8.78,11.3,3);
INSERT INTO TRAIT_STK (TRAIT_STK_ID,STK_ID,TRAIT_STK_RTN,TRAIT_STK_VOL,TRAIT_STK_RISK)
    VALUES (trait_stk_seq.nextval,4,7.78,4.4,2);
INSERT INTO TRAIT_STK (TRAIT_STK_ID,STK_ID,TRAIT_STK_RTN,TRAIT_STK_VOL,TRAIT_STK_RISK)
    VALUES (trait_stk_seq.nextval,5,6.78,5.1,2);
INSERT INTO TRAIT_STK (TRAIT_STK_ID,STK_ID,TRAIT_STK_RTN,TRAIT_STK_VOL,TRAIT_STK_RISK)
    VALUES (trait_stk_seq.nextval,6,5.78,8.3,3);
INSERT INTO TRAIT_STK (TRAIT_STK_ID,STK_ID,TRAIT_STK_RTN,TRAIT_STK_VOL,TRAIT_STK_RISK)
    VALUES (trait_stk_seq.nextval,7,13.78,23.2,3);
INSERT INTO TRAIT_STK (TRAIT_STK_ID,STK_ID,TRAIT_STK_RTN,TRAIT_STK_VOL,TRAIT_STK_RISK)
    VALUES (trait_stk_seq.nextval,8,14.78,18.9,3);
INSERT INTO TRAIT_STK (TRAIT_STK_ID,STK_ID,TRAIT_STK_RTN,TRAIT_STK_VOL,TRAIT_STK_RISK)
    VALUES (trait_stk_seq.nextval,9,17.78,31.6,3);
INSERT INTO TRAIT_STK (TRAIT_STK_ID,STK_ID,TRAIT_STK_RTN,TRAIT_STK_VOL,TRAIT_STK_RISK)
    VALUES (trait_stk_seq.nextval,10,10.01,10.12,3);
INSERT INTO TRAIT_STK (TRAIT_STK_ID,STK_ID,TRAIT_STK_RTN,TRAIT_STK_VOL,TRAIT_STK_RISK)
    VALUES (trait_stk_seq.nextval,11,10.03,7.1,2);
INSERT INTO TRAIT_STK (TRAIT_STK_ID,STK_ID,TRAIT_STK_RTN,TRAIT_STK_VOL,TRAIT_STK_RISK)
    VALUES (trait_stk_seq.nextval,12,11.99,14.98,3);
INSERT INTO TRAIT_STK (TRAIT_STK_ID,STK_ID,TRAIT_STK_RTN,TRAIT_STK_VOL,TRAIT_STK_RISK)
    VALUES (trait_stk_seq.nextval,13,2.78,1.2,1);
INSERT INTO TRAIT_STK (TRAIT_STK_ID,STK_ID,TRAIT_STK_RTN,TRAIT_STK_VOL,TRAIT_STK_RISK)
    VALUES (trait_stk_seq.nextval,14,5.78,2.6,1);
INSERT INTO TRAIT_STK (TRAIT_STK_ID,STK_ID,TRAIT_STK_RTN,TRAIT_STK_VOL,TRAIT_STK_RISK)
    VALUES (trait_stk_seq.nextval,15,6.78,5.4,2);
INSERT INTO TRAIT_STK (TRAIT_STK_ID,STK_ID,TRAIT_STK_RTN,TRAIT_STK_VOL,TRAIT_STK_RISK)
    VALUES (trait_stk_seq.nextval,16,3.22,2.3,1);
INSERT INTO TRAIT_STK (TRAIT_STK_ID,STK_ID,TRAIT_STK_RTN,TRAIT_STK_VOL,TRAIT_STK_RISK)
    VALUES (trait_stk_seq.nextval,17,6.44,7.1,2);
    
COMMIT;
                   