INSERT INTO TRAIT_REC_SEC (TRAIT_REC_SEC_ID, SEC_ID, TRAIT_SEC_RISK, IS_REC)
SELECT
    TRAIT_REC_SEC_SEQ.NEXTVAL,
    SEC_ID,
    CASE
        WHEN SEC_RISK > 0 AND SEC_RISK <= 1 THEN 1
        WHEN SEC_RISK > 1 AND SEC_RISK <= 2 THEN 2
        WHEN SEC_RISK > 2 THEN 3
        ELSE NULL
    END AS TRAIT_SEC_RISK,
    CASE
         -- 위험도 3 이하
        WHEN SEC_RISK <= 3 AND RANK() OVER (PARTITION BY CASE WHEN SEC_RISK <= 3 THEN 1 END ORDER BY TRAIT_SEC_RTN DESC) <= 3 THEN 3
        -- 위험도 2 이하
        WHEN SEC_RISK <= 2 AND RANK() OVER (PARTITION BY CASE WHEN SEC_RISK <= 2 THEN 1 END ORDER BY TRAIT_SEC_RTN DESC) <= 3 THEN 2
        -- 위험도 1 이하
        WHEN SEC_RISK <= 1 AND RANK() OVER (PARTITION BY CASE WHEN SEC_RISK <= 1 THEN 1 END ORDER BY TRAIT_SEC_RTN DESC) <= 3 THEN 1
        
        ELSE 0  -- 기본값
    END AS IS_REC
FROM
    TRAIT_SEC;
    
    ROLLBACK;
    
    
SELECT *
FROM TRAIT_REC_SEC;
