--CREATE SEQUENCE REC_STK_SEQ START WITH 1 INCREMENT BY 1;  


INSERT INTO REC_STK (REC_STK_ID, STK_ID, REC_RTN, REC_VOL, REC_RISK)
    VALUES (REC_STK_SEQ.NEXTVAL, 1, 10.78, 7.1, 2);
INSERT INTO REC_STK (REC_STK_ID, STK_ID, REC_RTN, REC_VOL, REC_RISK)
    VALUES (REC_STK_SEQ.NEXTVAL, 2, 9.78, 6.1, 2);
INSERT INTO REC_STK (REC_STK_ID, STK_ID, REC_RTN, REC_VOL, REC_RISK)
    VALUES (REC_STK_SEQ.NEXTVAL, 3, 8.78, 11.3, 3);
INSERT INTO REC_STK (REC_STK_ID, STK_ID, REC_RTN, REC_VOL, REC_RISK)
    VALUES (REC_STK_SEQ.NEXTVAL, 4, 7.78, 4.4, 2);
INSERT INTO REC_STK (REC_STK_ID, STK_ID, REC_RTN, REC_VOL, REC_RISK)
    VALUES (REC_STK_SEQ.NEXTVAL, 5, 6.78, 5.1, 2);
INSERT INTO REC_STK (REC_STK_ID, STK_ID, REC_RTN, REC_VOL, REC_RISK)
    VALUES (REC_STK_SEQ.NEXTVAL, 6, 5.78, 8.3, 3);
INSERT INTO REC_STK (REC_STK_ID, STK_ID, REC_RTN, REC_VOL, REC_RISK)
    VALUES (REC_STK_SEQ.NEXTVAL, 7, 13.78, 23.2, 3);
INSERT INTO REC_STK (REC_STK_ID, STK_ID, REC_RTN, REC_VOL, REC_RISK)
    VALUES (REC_STK_SEQ.NEXTVAL, 8, 14.78, 18.9, 3);
INSERT INTO REC_STK (REC_STK_ID, STK_ID, REC_RTN, REC_VOL, REC_RISK)
    VALUES (REC_STK_SEQ.NEXTVAL, 9, 17.78, 31.6, 3);
INSERT INTO REC_STK (REC_STK_ID, STK_ID, REC_RTN, REC_VOL, REC_RISK)
    VALUES (REC_STK_SEQ.NEXTVAL, 10, 10.01, 10.12, 3);
INSERT INTO REC_STK (REC_STK_ID, STK_ID, REC_RTN, REC_VOL, REC_RISK)
    VALUES (REC_STK_SEQ.NEXTVAL, 11, 10.03, 7.1, 2);
INSERT INTO REC_STK (REC_STK_ID, STK_ID, REC_RTN, REC_VOL, REC_RISK)
    VALUES (REC_STK_SEQ.NEXTVAL, 12, 11.99, 14.98, 3);
INSERT INTO REC_STK (REC_STK_ID, STK_ID, REC_RTN, REC_VOL, REC_RISK)
    VALUES (REC_STK_SEQ.NEXTVAL, 13, 2.78, 1.2, 1);
INSERT INTO REC_STK (REC_STK_ID, STK_ID, REC_RTN, REC_VOL, REC_RISK)
    VALUES (REC_STK_SEQ.NEXTVAL, 14, 5.78, 2.6, 1);
INSERT INTO REC_STK (REC_STK_ID, STK_ID, REC_RTN, REC_VOL, REC_RISK)
    VALUES (REC_STK_SEQ.NEXTVAL, 15, 6.78, 5.4, 2);
INSERT INTO REC_STK (REC_STK_ID, STK_ID, REC_RTN, REC_VOL, REC_RISK)
    VALUES (REC_STK_SEQ.NEXTVAL, 16, 3.22, 2.3, 1);
INSERT INTO REC_STK (REC_STK_ID, STK_ID, REC_RTN, REC_VOL, REC_RISK)
    VALUES (REC_STK_SEQ.NEXTVAL, 17, 6.44, 7.1, 2);    

COMMIT;    
    